# Generated by Django 3.1.6 on 2021-03-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_chess',
            name='chat_of_game',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
