# Generated by Django 3.1.6 on 2021-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_game_chess_chat_of_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_chess',
            old_name='analyse_list_move',
            new_name='analyse_list_move_komodo',
        ),
        migrations.AddField(
            model_name='game_chess',
            name='analyse_list_move_lc0',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='game_chess',
            name='analyse_list_move_stockfish',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
